### ISSUE TITLE
Encoding issue (on Python 2.7)

### ISSUE THREAD

**Issue by AndiH** [AndiH/rsync-by-config#11]
Add encoding prefix at top of rbc.py file

**Comment by ccalaza** [comment]
(Python version 2.7.9) After installing, when issuing the command "rbc --help" from the shell the following output is shown:

```
Traceback (most recent call last):
  File "/home/homeGlobal/ccalaza/.local/bin/rbc", line 9, in <module>
    load_entry_point('rsync-by-config==3.1', 'console_scripts', 'rbc')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/home/homeGlobal/ccalaza/.local/bin/rbc.py", line 210
SyntaxError: Non-ASCII character '\xc2' in file /home/homeGlobal/ccalaza/.local/bin/rbc.py on line 210, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by AndiH** [comment]
This should be fixed by adding
```
# -*- coding: utf-8 -*
```
as a second line to `rbc.py`
